### ISSUE TITLE
Duplicate SPA rule

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#106]
If you make a duplicate SPA condition, but with a separate effect, both nodes are created, but only the last effect is implemented. See the code below for an example:

```
import nengo_spa as spa

dimensions = 16

with spa.Network() as model:
    # Specify the modules to be used
    model.vision = spa.Transcode(output_vocab=dimensions)
    model.motor = spa.State(dimensions)
    
    # Specify the action mapping
    actions = spa.Actions('''
        ifmax dot(model.vision, A):
            A -> model.motor
        elifmax dot(model.vision, B):
            A -> model.motor
        elifmax dot(model.vision, B):
            B -> model.motor
    ''')
```

I feel like this should be an error, as I can't imagine making the same condition twice on purpose.

**Comment by jgosmann** [comment]
When I look at it in Nengo GUI it seems to me that both effects are implemented correctly. Though, the basal ganglia should allow only one effect to take effect.

**Comment by jgosmann** [comment]
I'm planning to do one more bugfix release of the 0.3 series (to fix the comment stuff) before the syntax gets replaced in 0.4. Do you think there is something here that should be done for that bugfix release? I am leaning towards closing this issue because to me there seems to be no bug.
