### ISSUE TITLE
When creating SPA node inputs, automatically convert to array

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_spa#12]
(Copied from nengo/nengo#661.)

At this point, when you want to use SPA as an input to a network, you have to call the somewhat awkward `.v` attribute as demonstrated in the code below.

```
import nengo

model = nengo.Network()
with model:
    a = nengo.networks.EnsembleArray(n_neurons=100, n_ensembles=16, ens_dimensions=1)
    def my_input(t):
        if t < 0.1:
            return vocab.parse('HELLO').v
        else:
            return vocab.parse('BYE').v

    nengo.Connection(nengo.Node(my_input), a.input)
```

Is there any way to automatically convert to a vector so this doesn't need to be called? The reason I believe this is possible is that numpy seems to transparently convert between arrays and python lists all the time.

**Comment by tcstewar** [comment]
There have been many times where I wished I'd implemented `pointer.py` such that I didn't need that `.v`....    I think if we just have the pointer object support `__item__` or `__iter__` that would work, but I don't know if that would cause confusion with the other ways we're using it....  I don't think it'd be a problem, though.

**Comment by jgosmann** [comment]
Tagging @Seanny123 who originally opened this issue.

I thought about dropping the need for `.v`, but decided against it because of the following reasons:
* `.v` is not much effort to type
* It makes it clear when we use NumPy semantics and when we use SemanticPointer semantics. For example `*` will do an elementwise multiply in NumPy, but a circular convolution with semantic pointers. So there needs to always be a way to access the NumPy semantics separately from the SemanticPointer semantics.
* When implementing `__getitem__` to allow direct access of single elements, it might give the impression the SemanticPointers behave with NumPy semantics.
* The provided example provides an input to a network. I'm currently looking into reimplementing `spa.Input` to act more like a node and to the conversion from SemanticPointer to NumPy array automatically which should cover that particular use case.

**Comment by Seanny123** [comment]
I agree with all the points you've raised @jgosmann. Thank you for taking such a thoughtful approach to this problem.

**Comment by tcstewar** [comment]
Those are very good points.  Thank you for looking into this!
