### ISSUE TITLE
All caps vs. camel case debate

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_spa#44]
Currently many SPA examples use [ALL_CAPS](https://en.wikipedia.org/wiki/All_caps) for semantic pointers. I think nengo_spa gives us the opportunity to rethink this choice and potentially switch to [CamelCase](https://en.wikipedia.org/wiki/Camel_case) which I tend to prefer.

Contra ALL_CAPS:
* Feels like old 90's HTML. ;) (maybe that's a pro for some? :P)
* In my opinion worse readability for long (single) words. (But most semantic pointer names aren't long.)
* Names consisting out of multiple words are not as easily recognized as a single entity (they appear almost as multiple entities/pointers as the underscore is almost like a space).
* Slightly annoying to type.

Pro ALL_CAPS:
* The difference to all lowercase modules is more apparent and less easily missed which might matter for users learning nengo_spa.
* Camel case has worse readability for compounds of many words (but most semantic pointers are just on word).

I suppose this could end up to be a very opinionated discussion as most arguments will not be absolute facts, but might still be worth having as it shapes how nengo_spa code is perceived. Personally I prefer camel case, but to me the first pro all caps point is also a strong argument.

**Comment by jgosmann** [comment]
@tcstewar, do you want to comment on this?

**Comment by tcstewar** [comment]
I think I'm still on the ALL_CAPS side, mostly for the reasons you've listed above, plus I also like that in Python ALL_CAPS is used for constants, which is kinda like a semantic pointer (or at least a lot more like a semantic pointer than a class is, and every time I look at a CamelCase variable I first think it's a class....)  This might be even more of an important consideration with the `inspective-parsing` stuff....

**Comment by bjkomer** [comment]
For me which one I prefer depends a lot on the situation. For more control oriented pointers I tend to like all caps (SEARCH, THINK, MOVE, etc) and for more thing related pointers I like camel case (Monkey, Banana, WaterBottle, etc). Now that I think of it, it's almost a unitary vs. non-unitary vector distinction in many cases.

**Comment by jgosmann** [comment]
Even though I don't like the look of the ALL_CAPS, the arguments to use ALL_CAPS seem to be stronger. So let's stick with it at least for the official examples and documentation.
