### ISSUE TITLE
Allow action rules to create states

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_spa#47]
It might make sense to autmatically create a `spa.State` `state` in an action rule of the the style `state = ...`. The vocabulary probably needs to be derived from the expression in that case and it probably would not allow for setting other parameters on the state. But it might make it easier to construct large models because not each intermediary state needs to be defined beforehand.

**Comment by jgosmann** [comment]
Given the new syntax a rule like `source -> target` would create `target` as a `State` with default parameters. If we allow chaining (#76), this would extend to create `target1` and `target2` in `source -> target1 -> target2`. However, it is not clear whether to allow to create states in the `source` expression.

Overall, this all feels very magical to me and only saves some typing if the `spa.State` use default parameters.

@tbekolay @astoeckel @xchoo share your thoughts!

**Comment by tbekolay** [comment]
While it does feel magical, the action rule syntax is pretty much all magic, so I don't see a problem with it. It seems to me like the action syntax is essentially a DSL for making SPA models, so might was well continue in that direction.

**Comment by jgosmann** [comment]
One more concern: Typos would be more likely to go unnoticed.

**Comment by jgosmann** [comment]
Decision from the dev meeting: Let's not do this. We are too worried about typos going unnoticed.
