### ISSUE TITLE
Should it be possible to chain connections in SPA action syntax?

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_spa#76]
Given the new connection operator '->' for SPA action rules, it seems like one could expect chaining like `state1 -> state2 -> state3` to work. At the moment one has to do `state1 -> state2; state2 -> state3`.

Do we want to allow such chaining?

**Comment by jgosmann** [comment]
Tagging those who were involved in the original syntax discussion: @tcstewar @astoeckel @xchoo

**Comment by jgosmann** [comment]
Important detail only the left-most expression might be something complex. For example, one could do `2 * stateA + stateB -> state2 -> state3`, but not `state1 -> 2 * stateA + stateB -> state3` because in the latter case it would not be clear what  `state1` would feed into.

**Comment by tcstewar** [comment]
Hmm, I've never wanted something like that, so it feels like it complicates the syntax without giving an advantage.  Are there use cases for this sort of thing?  I just can't think of them right now....

**Comment by jgosmann** [comment]
Maybe something where you have `state1 -> gate -> state2` and manually inhibit `gate`? I have things like that in my TCM model, but there I also do not use `spa.Actions` at all, but create all connections manually.

The advantage is basically less typing, but only in specific cases (where the middle module's default input and output are used).

I don't feel strongly about it. So maybe it is better to be conservative for now and don't allow it.

**Comment by jgosmann** [comment]
@celiasmith made the case for simplicity in the dev meeting. If we find that such chaining is used a lot, it can still be added later. Closing for now.
