### ISSUE TITLE
Add attribute to ASTAccessor to access BG and Thal

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#80]
Given an `ASTAccessor` can have `(0, N]` basal ganglias and thalamus, would it be helpful to provide a list of them? It comes up a lot for plotting in the examples. I'd imagine something like:
```
actions = spa.Actions('...')
bgs = actions.bg_loops()
thals = actions.thal_loops()
```

**Comment by jgosmann** [comment]
We decided in the dev meeting to provide different `all_*` accessor functions that generalize also to other SPA modules. I suppose pluralization might still be an issue:
* `all_bgs`, `all_thals`?
* `all_basal_ganglia`, `all_thalami`?
* `all_thalamus`? `all_thalamuses`? `all_thalamic_nuclei`?
* `vall_bg_nets`, `all_thalamus_nets`?

**Comment by tcstewar** [comment]
Hmm, pluralization is weird for both of them....  I'd vote for `all_bgs`/`all_thals` as my first choice, followed by `all_bg_nets`/`all_thal_nets`.....

**Comment by jgosmann** [comment]
Reopening as reminder to implement accessors for other modules than BG/Thalamus.

**Comment by jgosmann** [comment]
The original issue is resolved. I will open a new issue for other modules.
