### ISSUE TITLE
Basal Ganglia networks are not labeled

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#84]
Running this code in the Nengo GUI:

```
import nengo
import nengo_spa as spa

num_vocab = spa.Vocabulary(16)
num_vocab.populate("ZERO; ONE")

with spa.Network() as model:

    model.motor_mag = spa.Scalar()

    model.running = spa.Transcode(input_vocab=num_vocab, output_vocab=num_vocab)
    model.scal = spa.Scalar()

    spa.Actions("""
        ifmax model.motor_mag as 'motor':
            ZERO -> model.running
        ifmax model.scal as 'scal':
            ONE -> model.running
    """)
```

Gives the following network:

![selection_007](https://user-images.githubusercontent.com/1918825/32191594-0241c856-bd88-11e7-9c5e-e2606f66151e.png)

This is because the Basal Ganglia networks are not labeled, even though the Thalamus networks are:
```
In [3]: af = actions[0] 

In [6]: af.bg.label is None
Out[6]: True

In [8]: af.thalamus.label
Out[8]: 'Thalamus'
```

Additionally, I think the Basal Ganglia and Thalamus networks should incorporate the label given by the `as` keyword? Something like `Thalamus (scal)` from the previous example?

**Comment by jgosmann** [comment]
> Additionally, I think the Basal Ganglia and Thalamus networks should incorporate the label given by the as keyword? Something like Thalamus (scal) from the previous example?

There is no 1:1 correspondence ... not sure what the best way to deal with that would be.

**Comment by jgosmann** [comment]
> Additionally, I think the Basal Ganglia and Thalamus networks should incorporate the label given by the as keyword? Something like Thalamus (scal) from the previous example?
> 
> There is no 1:1 correspondence ... not sure what the best way to deal with that would be.

Any comments/proposals? @Seanny123 @tcstewar ?

**Comment by Seanny123** [comment]
> There is no 1:1 correspondence ... not sure what the best way to deal with that would be.

I revoke my suggestion. Appending all the labels together would be ugly as hell. Once we figure out how to create the basal ganglia or thalamus accessor properly, we can just use the label from that object and it will be easy to set so it won't be a problem.

I think this issue can be closed?
