### ISSUE TITLE
What's the difference between free-floating rule and always

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#87]
What's the difference between:

```
import nengo_spa as spa

num_vocab = spa.Vocabulary(16)
num_vocab.populate("ZERO; ONE; TWO")

with spa.Network() as model:

    model.motor_mag = spa.Scalar()

    model.running = spa.Transcode(input_vocab=num_vocab, output_vocab=num_vocab)
    model.scal = spa.Scalar()
    model.other = spa.State(num_vocab)

    actions = spa.Actions("""
        ifmax model.motor_mag as 'motor':
            ZERO -> model.running
            ZERO -> model.other

        ifmax model.scal as 'scal':
            ONE -> model.running
            ONE -> model.other

        always:
            TWO -> model.other
    """)
``

and 

```
import nengo_spa as spa

num_vocab = spa.Vocabulary(16)
num_vocab.populate("ZERO; ONE; TWO")

with spa.Network() as model:

    model.motor_mag = spa.Scalar()

    model.running = spa.Transcode(input_vocab=num_vocab, output_vocab=num_vocab)
    model.scal = spa.Scalar()
    model.other = spa.State(num_vocab)

    actions = spa.Actions("""
        TWO -> model.other

        ifmax model.motor_mag as 'motor':
            ZERO -> model.running
            ZERO -> model.other

        ifmax model.scal as 'scal':
            ONE -> model.running
            ONE -> model.other
    """)
```

I was talking to @tcstewar about this and he said that one of these should be an error? But neither of them cause an error on compilation.

**Comment by jgosmann** [comment]
There is no difference (except maybe in the AST and that an `always` block can be named.)

**Comment by tcstewar** [comment]
> There is no difference (except maybe in the AST and that an always block can be named.)

Do we want to have two different ways of doing the same thing?  I'm usually okay with that, but I get yelled at a lot for doing so...  ;)

**Comment by Seanny123** [comment]
*Very personally* I would then elect for the elimination of the `always` block. Because:

1. It confused me.
2. It seems semi-obvious that anything not within an `ifmax` block would be executed unconditionally.

**Comment by jgosmann** [comment]
I suppose the reason for adding at it was that it allows to name rules. That would not be possible without, but was a thing supported in the old SPA system (albeit in a somewhat different way). But that doesn't mean we have to keep that functionality, but if we removed it, I would probably also remove the possibility to name `ifmax` blocks.

**Comment by Seanny123** [comment]
I **really** like being able to name `ifmax` blocks because it allows for nice labeling when creating basal ganglia and thalamus plots in the Nengo GUI and otherwise. This doesn't apply to cortical connections, since they don't have their own associated plots. Consequently, I feel justified in saying to keep the ability to label `ifmax` blocks, while also removing the `always` block.

**Comment by jgosmann** [comment]
> it allows for nice labeling when creating basal ganglia and thalamus plots in the Nengo GUI and otherwise.

Not at the moment without access to the `spa.Actions` return value ... (maybe some time in the future?)

**Comment by Seanny123** [comment]
Yeah. I should specify I meant sometime in the future.

**Comment by jgosmann** [comment]
I came to the conclusion that the `as 'name'` feature is not very well thought out at the moment and mostly a relict of the legacy SPA. Thus I propose to remove `always` blocks and the ability to name `ifmax` for the time being.

If you do not want to access the individual rules of `spa.Actions` by numerical indices, create multiple `spa.Actions` and assign them to different named variables (this was not possible in the legacy SPA).

I still see a potential need to assign names to or access more fine grained parts of the AST or objects constructed from it. But this is a more general problem and I would like a more general solution than a one-off syntax for naming individual conditions. For example, in the expression
```
ifmax dot(a, A):
    stimulus * context + memory -> memory2
```
I might want to access (or name) the objects created by `stimulus * context`.

I agree that names for the conditions can be useful in the GUI, but at the moment (and the near future?) they will not be used there. In case we want to go with the current syntax in the future, it can be recovered from Git and easily added. If we decide against it in the future it is much more hassle to deprecate that syntax and remove it.

**Comment by Seanny123** [comment]
Just to make sure I understand, I'm going to try to explain what you've told me back to you:

1. We're going to remove `always` from the syntax definition, because it is indeed confusing.
2. We don't know what the bg/thal plot is going to look like in the Nengo GUI and we can always add it later. Since this was the only motivation for keeping the `as` keywords for labeling conditions, we're going to remove it. We will revisit how to label conditions later once we've defined that plot.

**Comment by jgosmann** [comment]
Yes, and regarding 2: if we decide at that time that the `as` syntax is what makes sense for that, I'm fine with adding it back in then.

**Comment by Seanny123** [comment]
Going through the documentation, I'm once again finding motivation for wanting to create a label for basal ganglia conditions, as well as thalamus effects.

For example, consider the following action set:
```
    actions = spa.Actions('''
        ifmax dot(model.vision, STATEMENT):
            model.vision - STATEMENT -> model.statement
            model.statement -> model.memory
        elifmax dot(model.vision, QUESTION):
            model.vision - QUESTION -> model.question
            ~(model.question)*model.memory -> model.motor
    ''')
```

Typically, when I want to label a matplotlib plot with those actions, I can do something hacky like:
```
plt.legend([str(a.effects) for a in actions[0].actions], fontsize='x-small', loc='right')
plt.legend([str(a.condition) for a in actions[0].actions], fontsize='x-small', loc='right')
```
But those labels aren't as ideal as the ones I could provide myself.

This is also useful for labeling modules in the Nengo GUI in a better way. Currently, Thalamus channels are labeled by the effect that created them, but this can be a really long and ugly string. It would be better if I could provide my own label.

There is the option of labeling these individually after the actions have been built, but that's annoying, because if I add a new actions, the indices will get mixed up. Unless there's some way to understandably and uniquely give a key to each action after it's created? That seems difficult to do in a human-readable manner.

I can't think of anyway to do this other than the `as` keyword. Or maybe making specialized comments? Specialized comments feel worse than built-in keywords.

**Comment by jgosmann** [comment]
I have been thinking a little bit more about alternative ways of naming and came up with two ideas

### Builtin function

We could add a built-in function that would not just allow to name the conditions, but also expressions and subparts of it like so:

```
ifmax named('foo', dot(a, b)):
    named('circconv', a * b) -> c
elifmax dot(a, A) + named('bar', dot(b, B)):
    A * named('baz', a + b) + c -> named('sink', d)
```
I like that this would allow us to put the (potentially more descriptive name) in front of the actual condition.
However, to allow this for a whole effect like `named('effect', a -> b)` might be complicated to implement. It also does not allow to name multiple lines (but maybe that's ok).

### variable assignment

Allow to assign expressions to variables and to reuse them later in the rules.

```
foo = dot(a, b)
circconv = a * b
bar = dot(b, B)
baz = a + b
sink = d
effect = a -> b

ifmax foo:
    circconv -> c
elifmax dot(a, A) + bar:
    A * baz + c -> sink
```

This would give a natural way of reusing repeated components. A bit more thought might have to go into how named effects (`effect = a -> b`) are handled. What should happen if they are repeated in different ifmax clauses? (The answer is probably the effect gets constructed when it is assigned and the assigned variable cannot be used.)

One disadvantge is that names in this way get restricted to valid Python identifiers.

Again naming multiple lines is not supported by this approach.

**Comment by Seanny123** [comment]
I like the built-in function the most. Would you care to elaborate why wrapping a whole effect might be difficult?

**Comment by jgosmann** [comment]
Because we don't define the whole grammar for expressions. For an expression we just read all tokens until a delimiting character (`->`, newline, EOF, etc.) and let Python do the work. In the grammar itself a `effect_line` is then just `expr -> expr`. If we were to allow `named('str', expr -> expr)`, we have effects embeded in expression which means we need to parse the effect line as an expression and figure out where we have `expr -> expr` constructs to parse those as effect. There might be ways that require not a whole lot of work, but I would consider those hacks. The proper way would require us to specify the grammar with a whole lot more detail which is a lot of effort and error prone (c.p. how easy it was to miss a lot of places where comments can go).

**Comment by jgosmann** [comment]
Both the builtin function approach and variable naming approach could be integrated with the object-based action interface (#108) that we are moving to. We will reconsider this issue once that is implemented.

**Comment by Seanny123** [comment]
This no longer occurs in the new actions syntax, so I'm closing this issue.
