### ISSUE TITLE
Somehow include syntax highlighting for action strings

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#91]
I don't know how to make syntax highlighters. Worse, I don't know how to make a syntax highlighter in a way that minimizes the work required to work across different editors. However, I do think it would be useful to define a syntax highlighter for the `spa.Actions` strings. Maybe a good start would be to build something for the Ace Editor, since that's what we use in Nengo GUI? Also, if we only support a single editor, we can always tell people to use that editor if they're building such a huge collection of `spa.Actions` that they need syntax highlighting desperately?

I'm making this issue mostly as a discussion to determine how hard this would actually be. At this point, I'm assuming it would be ridiculously time consuming, but I thought I would check my assumptions.

**Comment by jgosmann** [comment]
Made a PR for Nengo GUI. Also wrote a syntax highlighting file for Vim. To use save it as `~/.vim/after/syntax/python.vim`:

```vim
syn clear pythonAttribute pythonMatrixMultiply pythonDoctest
syn match pythonAttribute /\.\h\w*/hs=s+1  transparent contains=ALLBUT,@spa,pythonBuiltin,pythonFunction,pythonAsync
syn match pythonMatrixMultiply /\%(\w\|[])]\)\s*@/  transparent contains=ALLBUT,@spa,pythonDecoratorName,pythonDecorator,pythonFunction,pythonDoctestValue
syn match pythonMatrixMultiply /[^\\]\\\s*\n\%(\s*\.\.\.\s\)\=\s\+@/  transparent contains=ALLBUT,@spa,pythonDecoratorName,pythonDecorator,pythonFunction,pythonDoctestValue
syn match pythonMatrixMultiply /^\s*\%(\%(>>>\|\.\.\.\)\s\+\)\=\zs\%(\h\|\%(\h\|[[(]\).\{-}\%(\w\|[])]\)\)\s*\n\%(\s*\.\.\.\s\)\=\s\+@\%(.\{-}\n\%(\s*\.\.\.\s\)\=\s\+@\)*/  transparent contains=ALLBUT,@spa,pythonDecoratorName,pythonDecorator,pythonFunction,pythonDoctestValue
syn region pythonDoctest start=/^\s*>>>\s/ end=/^\s*$/  contained contains=ALLBUT,@spa,pythonDoctest,pythonFunction,@Spell

syn keyword spaBuiltin dot reinterpret translate contained
syn keyword spaConnect -> contained
syn keyword spaIfMax ifmax elifmax contained
syn match spaPointer /\<[A-Z][_a-zA-Z0-9]*\>/ contained

syn cluster spa contains=spaBuiltin,spaConnect,spaIfMax,spaPointer
syn region spaActions matchgroup=spaActionsBoundary start=/spa\(\s\|\n\)*\.\(\s\|\n\)*Actions\(\s\|\n\)*(\(\s\|\n\)*[uUrR]\=\z('''\|\'\|"""\|"\)/ end=/\z1\(\s\|\n\)*)/ contains=ALLBUT,pythonDoctestValue,pythonFunction

highlight def link spaBuiltin pythonBuiltin
highlight def link spaConnect Operator
highlight def link spaIfMax Conditional
highlight def link spaActionsBoundary Statement
highlight def link spaPointer Type
```

It has some similar limitations as the syntax highlighting in the GUI. A little bit better handling of newlines in `spa.Actions(` (but forgot to account for the line continuation character `\`).

Here is what it looks like with the [Solarized](http://ethanschoonover.com/solarized) color scheme in Vim:
<img width="600" alt="vim" src="https://user-images.githubusercontent.com/850157/32411639-07cab994-c1b7-11e7-8502-73321a86e3e3.png">

**Comment by Seanny123** [comment]
This is awesome! I'm currently trying to see if I can somehow [convert your rule to run in PyCharm](https://stackoverflow.com/q/47123823/1079075).

**Comment by Seanny123** [comment]
Closing this issue as we no longer have this problem with the new syntax.
