### ISSUE TITLE
Unused arguments

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#94]
Found some unused arguments that might need to be removed?

1. [`constructed` in `ConstructionContext`](https://github.com/nengo/nengo_spa/blob/master/nengo_spa/compiler/ast.py#L112)
2.  [`intercept_width` in `IA`](https://github.com/nengo/nengo_spa/blob/master/nengo_spa/networks/selection.py#L10)

**Comment by jgosmann** [comment]
1. Yeah, that should be removed if all the tests still pass. If the tests fail, it probably should still be removed and other stuff fixed.
2. This should actually be used, but I forgot to pass it through.
